- hosts: tag_AnsibleGroup_appdbs
  name: Configure the Database Servers
  gather_facts: true


- hosts: tag_AnsibleGroup_appdbs
  name: Install PostGreSQL
  gather_facts: true
  become: yes
  tasks:

  - name: Install PostGreSQL
    yum: 
      name: postgresql-server
      state: latest

  - name: Start and Enable PostGreSQL service
    service: 
      name: postgresql-server 
      state: started 
      enabled: yes

