- hosts: jumphost
  name: Log on to JumpHost
  gather_facts: false


- hosts: tag_AnsibleGroup_apps
  name: Install App Servers
  gather_facts: true
  become: yes
  tasks:
  - name: Install package
    yum: name=httpd state=latest
  - name: Start and Enable httpd service
    service: name=httpd state=started enabled=yes
  - name: Create index.html
    copy:
     content: "Hello World"
     dest: /var/www/html/index.html
